---
- name: Install unzip and acl (Debian/Ubuntu)
  apt:
    name:
      - unzip
      - acl
    state: present

- name: Ensure user smartfox exists
  user:
    name: "smartfox"
    shell: /bin/false
    home: "{{ smartfox_target_directory }}"
    state: present
    system: yes