---
- name: Install unzip and acl (Debian/Ubuntu)
  apt:
    name:
      - unzip
      - acl
      - python3-pip
    state: present

- name: Install lxml
  pip:
    name: lxml
    state: present

- name: Ensure user smartfox exists
  user:
    name: "{{ smartfox_user }}"
    shell: /bin/false
    home: "{{ smartfox_target_directory }}"
    state: present
    system: yes